version: 2
updates:
  - package-ecosystem: "pip"
    directory: "application/"
    schedule:
      interval: "weekly"
      day: "friday"
    labels:
      - "Dependabot"
      - "dependencies"
      - "application"
    open-pull-requests-limit: 10
